apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: &app ${artifactName}
  app.kubernetes.io/name: *app
  app.kubernetes.io/instance: *app
  app.kubernetes.io/component: backend
  app.openshift.io/runtime: quarkus

resources:
- deployment.yaml
- route.yaml
- service.yaml